common_args:
  exp_config_name: "virnyflow_task"
  run_nums: [1]
  save_storage: false
  secrets_path: "./configs/secrets.env"  # do not change this path since it is static for a docker container

pipeline_args:
  dataset: "diabetes"
  sensitive_attrs_for_intervention: ["<SENSITIVE_ATTRIBUTE>"]
  null_imputers: []
  fairness_interventions: []
  models: ["lr_clf", "rf_clf", "lgbm_clf"]

optimisation_args:
  ref_point: [0.20, 0.20]
  objectives:
    - { name: "objective_1", metric: "F1", group: "overall", weight: 0.5 }
    - { name: "objective_2", metric: "<FAIRNESS_METRIC>", group: "<SENSITIVE_ATTRIBUTE>", weight: 0.5 }
  optimizer:
    surrogate_type: 'auto'
    acq_type: 'auto'
    acq_optimizer_type: 'auto'
  max_total_pipelines_num: 30  # or we can use max_time_budget to set an execution budget in seconds
  num_workers: 2
  num_pp_candidates: 2  # set also in docker-compose.yaml
  training_set_fractions_for_halting: [0.5, 1.0]
  exploration_factor: 0.5
  risk_factor: 0.5

virny_args:
  sensitive_attributes_dct: {'<SENSITIVE_ATTRIBUTE>': '<DISADVANTAGED_VALUE>'}
